let users =[
    {
        login: "acenelio",
        id: 13897257,
        node_id: "MDQ6VXNlcjEzODk3MjU3",
        imgUrl: "https://avatars.githubusercontent.com/u/13897257?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/acenelio",
        html_url: "https://github.com/acenelio",
        followers_url: "https://api.github.com/users/acenelio/followers",
        following_url: "https://api.github.com/users/acenelio/following{/other_user}",
        gists_url: "https://api.github.com/users/acenelio/gists{/gist_id}",
        starred_url: "https://api.github.com/users/acenelio/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/acenelio/subscriptions",
        organizations_url: "https://api.github.com/users/acenelio/orgs",
        repos_url: "https://api.github.com/users/acenelio/repos",
        events_url: "https://api.github.com/users/acenelio/events{/privacy}",
        received_events_url: "https://api.github.com/users/acenelio/received_events",
        type: "User",
        user_view_type: "public",
        site_admin: false,
        name: "Nelio Alves",
        company: "@devsuperior",
        blog: "https://devsuperior.com.br",
        location: "Brazil",
        email: null,
        hireable: null,
        bio: "Ajudo estudantes e profissionais de programação a ingressar ou se recolocar na carreira.\r\n20 anos de experiência profissional, mais de 160 mil alunos online. ",
        twitter_username: null,
        public_repos: 286,
        public_gists: 0,
        followers: 12408,
        following: 1,
        created_at: "2015-08-21T03:24:45Z",
        updated_at: "2024-12-25T18:26:27Z"
      },

      {
        login: "AYRESRIO",
        id: 83145818,
        node_id: "MDQ6VXNlcjgzMTQ1ODE4",
        imgUrl: "https://avatars.githubusercontent.com/u/83145818?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/AYRESRIO",
        html_url: "https://github.com/AYRESRIO",
        followers_url: "https://api.github.com/users/AYRESRIO/followers",
        following_url: "https://api.github.com/users/AYRESRIO/following{/other_user}",
        gists_url: "https://api.github.com/users/AYRESRIO/gists{/gist_id}",
        starred_url: "https://api.github.com/users/AYRESRIO/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/AYRESRIO/subscriptions",
        organizations_url: "https://api.github.com/users/AYRESRIO/orgs",
        repos_url: "https://api.github.com/users/AYRESRIO/repos",
        events_url: "https://api.github.com/users/AYRESRIO/events{/privacy}",
        received_events_url: "https://api.github.com/users/AYRESRIO/received_events",
        type: "User",
        user_view_type: "public",
        site_admin: false,
        name: "Marcio D. Ayres",
        company: null,
        blog: "",
        location: null,
        email: null,
        hireable: null,
        bio: "I work hard to get a better life.",
        twitter_username: null,
        public_repos: 49,
        public_gists: 4,
        followers: 0,
        following: 0,
        created_at: "2021-04-25T00:25:17Z",
        updated_at: "2025-01-22T13:47:25Z"
      },

];

export function getUsers(){
    return(
        users
    );
}